routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome', ['name' => 'Hussein']);
});

Route::resource('group', 'GroupController');

Route::resource('contact', 'ContactController');


////////////////////////////////
Route::get('foo', function () {
    return 'Hello Hussein';
});



Route::get('user/{name?}', function ($name = "hussein") {
    return $name;
});

Route::resource('photos', 'PhotoController');

Route::get('blade', function () {
    return view('child');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    //
    public $fillable = ['title'];

    public function contacts(){
        return $this->belongsToMany('App\Contact','contacts_groups');
    }

}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\Group;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\Auth;


class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function index(Request $request){
        if(!Auth::check())
            return redirect()->intended('/');

        $groups = Group::orderBy('id','DESC')->paginate(10);

        return view('Group.index',compact('groups'))

            ->with('i', ($request->input('page', 1) - 1) * 5);

    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(!Auth::check())
            return redirect()->intended('/');

        return view('Group.create');
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){
        if(!Auth::check())
            return redirect()->intended('/');

        $this->validate($request, [

            'title' => 'required',


        ]);


        Group::create($request->all());

        return redirect()->route('group.index')

                        ->with('success','Group created successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if(!Auth::check())
            return redirect()->intended('/');

        $group = Group::find($id);

        return view('Group.show',compact('group'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(!Auth::check())
            return redirect()->intended('/');

        $group = Group::find($id);

        return view('Group.edit',compact('group'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        if(!Auth::check())
            return redirect()->intended('/');

        $this->validate($request, [

            'title' => 'required',

        ]);


        Group::find($id)->update($request->all());

        return redirect()->route('group.index')

                        ->with('success','Group updated successfully');

    }


    /**

     * Remove the specified resource from storage.

     *

     * @param  int  $id

     * @return \Illuminate\Http\Response

     */

    public function destroy($id){
        if(!Auth::check())
            return redirect()->intended('/');

        Group::find($id)->delete();

        return redirect()->route('group.index')

                        ->with('success','Group deleted successfully');

    }
}

resources/views/Group/create.blade.php
@extends('layouts.app')


@section('content')


    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Create New Group</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('group.index') }}"> Back</a>

            </div>

        </div>

    </div>


    @if (count($errors) > 0)

        <div class="alert alert-danger">

            <strong>Whoops!</strong> There were some problems with your input.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif


    {!! Form::open(array('route' => 'group.store','method'=>'POST')) !!}

    <div class="row">


        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Title:</strong>

                {!! Form::text('title', null, array('placeholder' => 'Title','class' => 'form-control')) !!}

            </div>

        </div>


        


        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

                <button type="submit" class="btn btn-primary">Submit</button>

        </div>


    </div>

    {!! Form::close() !!}


@endsection

resources/views/Group/edit.blade.php
@extends('layouts.app')

 

@section('content')


    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Edit New Group</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('group.index') }}"> Back</a>

            </div>

        </div>

    </div>


    @if (count($errors) > 0)

        <div class="alert alert-danger">

            <strong>Whoops!</strong> There were some problems with your input.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif


    {!! Form::model($group, ['method' => 'PATCH','route' => ['group.update', $group->id]]) !!}

    <div class="row">


        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Title:</strong>

                {!! Form::text('title', null, array('placeholder' => 'Title','class' => 'form-control')) !!}

            </div>

        </div>


        


        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

                <button type="submit" class="btn btn-primary">Submit</button>

        </div>


    </div>

    {!! Form::close() !!}


@endsection

resources/views/Group/index.blade.php
@extends('layouts.app')

 

@section('content')


    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>groups CRUD</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-success" href="{{ route('group.create') }}"> Create New group</a>

            </div>

        </div>

    </div>


    @if ($message = Session::get('success'))

        <div class="alert alert-success">

            <p>{{ $message }}</p>

        </div>

    @endif


    <table class="table table-bordered">

        <tr>

            <th>No</th>

            <th>Title</th>

            
            <th width="280px">Action</th>

        </tr>

    @foreach ($groups as $key => $group)

    <tr>

        <td>{{ ++$i }}</td>

        <td>{{ $group->title }}</td>

        

        <td>

            <a class="btn btn-info" href="{{ route('group.show',$group->id) }}">Show</a>

            <a class="btn btn-primary" href="{{ route('group.edit',$group->id) }}">Edit</a>

            {!! Form::open(['method' => 'DELETE','route' => ['group.destroy', $group->id],'style'=>'display:inline']) !!}

            {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}

            {!! Form::close() !!}

        </td>

    </tr>

    @endforeach

    </table>


    {!! $groups->render() !!}


@endsection

resources/views/Group/show.blade.php
@extends('layouts.app')

 

@section('content')


    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2> Show Group</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('group.index') }}"> Back</a>

            </div>

        </div>

    </div>


    <div class="row">


        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Title:</strong>

                {{ $group->title }}

            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-contact">

                <strong>Contacts:</strong>
                         <table class="table table-bordered">

                            <tr>
                                <th>name</th>            
                                <th >phone</th>
                            </tr>
                                @foreach ($group->contacts as $contact)

                            <tr>
                            
                            <td><a href="{!! url('contact', ['id' => $contact->id]); !!}">{{ $contact->name }}</a></td>

                            <td>{{ $contact->phone }}</td>
                            
                        </tr>

                        @endforeach

                        </table>

            </div>



        </div>



    </div>


@endsection