routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome', ['name' => 'Hussein']);
});

Route::resource('group', 'GroupController');

Route::resource('contact', 'ContactController');


////////////////////////////////
Route::get('foo', function () {
    return 'Hello Hussein';
});



Route::get('user/{name?}', function ($name = "hussein") {
    return $name;
});

Route::resource('photos', 'PhotoController');

Route::get('blade', function () {
    return view('child');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    //
    public $fillable = ['name','phone'];

    public function groups()
    {
        return $this->belongsToMany('App\Group','contacts_groups');
    }


	public function getGroupListAttribute()
    {
        return $this->groups()->pluck('id')->all();
    }
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Contact;
use App\Group;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\Auth;

class ContactController extends Controller
{
    /***/
    public function index(Request $request){

       if(!Auth::check())
            return redirect()->intended('/');

        $contacts = Contact::orderBy('id','DESC')->paginate(10);

        return view('Contact.index',compact('contacts'))

            ->with('i', ($request->input('page', 1) - 1) * 5);

    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(!Auth::check())
            return redirect()->intended('/');
        $group = Group::pluck('title', 'id')->all();
        
        return view('Contact.create',compact('group'));
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){
        if(!Auth::check())
            return redirect()->intended('/');

        $this->validate($request, [

            'name' => 'required',
            'phone' => 'required',
            'group' => 'required',


        ]);

        $data = $request->all();
        
        $contact = Contact::create($request->all());
        
        $contact->groups()->sync($data['group']);
        
        return redirect()->route('contact.index')

                        ->with('success','Contact created successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if(!Auth::check())
            return redirect()->intended('/');

        $contact = Contact::find($id);

        return view('Contact.show',compact('contact'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(!Auth::check())
            return redirect()->intended('/');

        $contact = Contact::find($id);

        $group = Group::pluck('title', 'id')->all();

        return view('Contact.edit',compact('contact','group'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        if(!Auth::check())
            return redirect()->intended('/');

        $this->validate($request, [

            'name' => 'required',
            'phone' => 'required',
            'group' => 'required',


        ]);


        

        $data = $request->all();
        
        $contact = Contact::find($id);
        $contact->update($data);
        $contact->groups()->sync($data['group']);


        return redirect()->route('contact.index')

                        ->with('success','Contact updated successfully');

    }


    /**

     * Remove the specified resource from storage.

     *

     * @param  int  $id

     * @return \Illuminate\Http\Response

     */

    public function destroy($id){

        if(!Auth::check())
            return redirect()->intended('/');

        Contact::find($id)->delete();

        return redirect()->route('contact.index')

                        ->with('success','Contact deleted successfully');

    }
}

resources/views/Contact/create.blade.php
@extends('layouts.app')


@section('content')


    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Create New Contact</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('contact.index') }}"> Back</a>

            </div>

        </div>

    </div>


    @if (count($errors) > 0)

        <div class="alert alert-danger">

            <strong>Whoops!</strong> There were some problems with your input.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif


    {!! Form::open(array('route' => 'contact.store','method'=>'POST')) !!}

    <div class="row">


        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-contact">

                <strong>Name:</strong>

                {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-contact">

                <strong>Phone:</strong>

                {!! Form::text('phone', null, array('placeholder' => 'Phone','class' => 'form-control')) !!}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-contact">

                <strong>Groups:</strong>

                {!! Form::select('group[]', $group,[],['class' => 'form-control', 'multiple' => 'multiple']) !!}

            </div>

        </div>


        


        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

                <button type="submit" class="btn btn-primary">Submit</button>

        </div>


    </div>

    {!! Form::close() !!}


@endsection

resources/views/Contact/edit.blade.php
@extends('layouts.app')

 

@section('content')


    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Edit New Contact</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('contact.index') }}"> Back</a>

            </div>

        </div>

    </div>


    @if (count($errors) > 0)

        <div class="alert alert-danger">

            <strong>Whoops!</strong> There were some problems with your input.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif


    {!! Form::model($contact, ['method' => 'PATCH','route' => ['contact.update', $contact->id]]) !!}

    <div class="row">


        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-contact">

                <strong>Name:</strong>

                {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-contact">

                <strong>Phone:</strong>

                {!! Form::text('phone', null, array('placeholder' => 'Phone','class' => 'form-control')) !!}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-contact">

                <strong>Groups:</strong>

                {!! Form::select('group[]', $group,$contact->groups,['class' => 'form-control', 'multiple' => 'multiple']) !!}

            </div>

        </div>


        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

                <button type="submit" class="btn btn-primary">Submit</button>

        </div>


    </div>

    {!! Form::close() !!}


@endsection

resources/views/Contact/index.blade.php
@extends('layouts.app')

 

@section('content')


    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Contacts</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-success" href="{{ route('contact.create') }}"> Create New contact</a>

            </div>

        </div>

    </div>


    @if ($message = Session::get('success'))

        <div class="alert alert-success">

            <p>{{ $message }}</p>

        </div>

    @endif


    <table class="table table-bordered">

        <tr>

            <th>No</th>

            <th>Name</th>

            <th>Phone</th>

            
            <th width="280px">Action</th>

        </tr>

    @foreach ($contacts as $key => $contact)

    <tr>

        <td>{{ ++$i }}</td>

        <td>{{ $contact->name }}</td>

        <td>{{ $contact->phone }}</td>

        

        <td>

            <a class="btn btn-info" href="{{ route('contact.show',$contact->id) }}">Show</a>

            <a class="btn btn-primary" href="{{ route('contact.edit',$contact->id) }}">Edit</a>

            {!! Form::open(['method' => 'DELETE','route' => ['contact.destroy', $contact->id],'style'=>'display:inline']) !!}

            {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}

            {!! Form::close() !!}

        </td>

    </tr>

    @endforeach

    </table>


    {!! $contacts->render() !!}


@endsection

resources/views/Contact/show.blade.php
@extends('layouts.app')

 

@section('content')


    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2> Show Contact</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('contact.index') }}"> Back</a>

            </div>

        </div>

    </div>


    <div class="row">


        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-contact">

                <strong>Name:</strong>

                {{ $contact->name }}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-contact">

                <strong>Phone:</strong>

                {{ $contact->phone }}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-contact">

                <strong>Groups:</strong>

                @foreach ($contact->groups as $group)
                    <a href="{!! url('group', ['id' => $group->id]); !!}">{{ $group->title }}</a>
                @endforeach

            </div>

        </div>


    </div>


@endsection